services:
  db:
    image: mysql:8.0
    container_name: db_base_system_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: db_base_system
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: backend_books_api
    environment:
      DATABASE_URL: "mysql://root@db:3306/db_base_system"
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
